export const FETCH_MY_BATTLES = "FETCH_MY_BATTLES";
export const FETCH_MY_BATTLES_SUCCESS = "FETCH_MY_BATTLES_SUCCESS";
export const FETCH_MY_BATTLES_FAIL = "FETCH_MY_BATTLES_FAIL";

export const FETCH_LOGS = "FETCH_LOGS";
export const FETCH_LOGS_SUCCESS = "FETCH_LOGS_SUCCESS";
export const FETCH_LOGS_FAIL = "FETCH_LOGS_FAIL";

export const RESET_BATTLE = "RESET_BATTLE";
export const RESET_BATTLE_SUCCESS = "RESET_BATTLE_SUCCESS";
export const RESET_BATTLE_FAIL = "RESET_BATTLE_FAIL";

export const NEW_BATTLE = "NEW_BATTLE";
export const NEW_BATTLE_SUCCESS = "NEW_BATTLE_SUCCESS";
export const NEW_BATTLE_FAIL = "NEW_BATTLE_FAIL";

export const NEW_ATTACK = "NEW_ATTACK";
export const NEW_ATTACK_SUCCESS = "NEW_ATTACK_SUCCESS";
export const NEW_ATTACK_FAIL = "NEW_ATTACK_FAIL";