export const FETCH_MY_BATTLES = "FETCH_MY_BATTLES";
export const FETCH_MY_BATTLES_SUCCESS = "FETCH_MY_BATTLES_SUCCESS";
export const FETCH_MY_BATTLES_FAIL = "FETCH_MY_BATTLES_FAIL";

export const FETCH_LOGS = "FETCH_LOGS";
export const FETCH_LOGS_SUCCESS = "FETCH_LOGS_SUCCESS";
export const FETCH_LOGS_FAIL = "FETCH_LOGS_FAIL";

export const RESET_BATTLE = "RESET_BATTLE";
export const RESET_BATTLE_SUCCESS = "RESET_BATTLE_SUCCESS";
export const RESET_BATTLE_FAIL = "RESET_BATTLE_FAIL";